### PR TITLE
Armadillo 8.100, call .sync() before accessing the internal arrays of the SpMat class

### PR DESCRIPTION
**Pull request by binxiangni**
I just call .sync() in as<>() and it works. But it seems a little weird that no error comes out when I don't call .sync() in wrap() before reading those internal arrays of the SpMat class.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Your tests may be missing the salient fact that we are *not* on Armadill 0.8[01]00.* yet.

**Comment by binxiangni** [comment]
So in addition to copying armadillo_bits to here and modifying as<>(), what else should I do?

**Comment by binxiangni** [comment]
I find that I don't need to call .sync() before arma::access::rwp, but I should call that before arma::access::rw, which possibly means no need to call .sync() before directly reading or writing the pointers. I guess that might explain my problem.

**Comment by eddelbuettel** [comment]
> So in addition to copying armadillo & armadillo_bits to here and modifying as<>(), what else should I do?

I think you can wait for more tests until I had a chance to update Armadillo within RcppArmadillo.

**Comment by eddelbuettel** [comment]
I am not at Armadillo 8.100.1.  I think I will need the first part of the PR -- as there are some errors -- but there are "issues" with this PR as it covers 80+ files it should not cover (from Armadillo 8.*).  Shall we / can we clean that up, or shall I just re-apply the relevant part by hand?

**Comment by eddelbuettel** [comment]
(Copying over.  Wrote this in #175 by mistake at first.)

This was a very important and timely PR. I had test failures due to SpMat changes, but with your syncing it passes.

Now it so happens that I cannot merge this now, but I will give you full credit in inst/NEWS.Rd. Hope that's ok.

I should have put 8.100.* into a branch earlier. My bad.

**Comment by eddelbuettel** [comment]
Ok, I folded this into #176 which is now being tested.

**Comment by binxiangni** [comment]
Sorry for being late to take action. Being busy with midterms. Kind of difficult to catch you up. So what should I do? As I see, you've removed the redundant files, right?

**Comment by eddelbuettel** [comment]
No real action item.  But if you and @sgsokol can look over the changes I made to [`RcppArmadilloAs.h`](https://github.com/RcppCore/RcppArmadillo/blob/arma-8.100.1/inst/include/RcppArmadilloAs.h) in the branch that is behind the #161 PR.  It is now running a rev.dep -- we should be good.

**Comment by binxiangni** [comment]
I checked it and my part should be fine. Thanks! (btw, the PR number above should be #176 )

**Comment by eddelbuettel** [comment]
Ooops. Correcting.

**Comment by sgsokol** [comment]
For me too, it looks OK.

**Comment by eddelbuettel** [comment]
Again, sorry to both of for sitting on the PRs in a way that then prevented me from merging them.

Lesson learned, I just should not wait for my next RcppArmadillo release cycle.

**Comment by eddelbuettel** [comment]
The content of this PR is now in master via #176.  Again my apologies for not merging this sooner (maybe into a branch with arma 8.*).

**Pull request closed without merging**
