### PR TITLE
use Rcpp vignette style

### PR DESCRIPTION
**Pull request by eddelbuettel**
@binxiangni I updated the vignette a little, see a [(temp) copy of the pdf](http://dirk.eddelbuettel.com/tmp/RcppArmadillo-sparseMatrix.pdf) for a quick glance.

### CODE REVIEW

**Comment by binxiangni** [comment]
Looks good. There might be an inconsistency due to me. [Subsection 2.7.3](https://github.com/RcppCore/RcppArmadillo/pull/153/commits/32996daffd5a27356d67c783470f6cd3adf490c0#diff-955b0f1df45f7bd7af41e6baabd2ad3eL405) includes `library(Matrix)`, but others don't. Maybe we can just remove it. The other part is great. You can merge it. Thank you!

**Comment by eddelbuettel** [comment]
> Maybe we can just remove it.

Done!

**Comment by eddelbuettel** [comment]
BTW, one downside is that you need a helper script such as the snippet below to compile the vignette.

```r
#!/usr/bin/Rscript

## use given argument(s) as target files, or else default to .Rnw files in directory
files <- if (length(commandArgs(TRUE)) == 0) dir(pattern="*.Rnw") else commandArgs(TRUE)

## convert all files from Rnw to pdf using the highlight driver
invisible(sapply(files, function(srcfile) {
    Sweave(srcfile, driver=highlight::HighlightWeaveLatex())
    tools::texi2pdf(gsub(".Rnw", ".tex", srcfile))
}))
```

**Comment by binxiangni** [comment]
Not familiar with that. I just compile my original one in Rstudio. Thanks for reminding. Really learned a lot from you this summer.

**Comment by eddelbuettel** [comment]
It's the non-standard (but perfectly fine and permitted) vignette we use: based on [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php).   All pretty easy on Linux, and (I presume) possible on macOS...

**Pull request merged**
