### PR TITLE
work in private build dir during configure

### PR DESCRIPTION
**Pull request by kevinushey**
Performs `R CMD SHLIB` in a private directory within the temporary directory (from `TMPDIR` if set; otherwise just `/tmp`) and then removes that directory.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Please see #295 which is in flight.  If you PR, can you possible PR against its branch, not `master`?

**Comment by eddelbuettel** [comment]
The build dir generalization is good.  I'll try to make time (in a day or two) to resolve the conflict due to us working on the same file at the same time, and get the change in.

**Comment by eddelbuettel** [comment]
Rebased, but need to check again it's all the way it is supposed to be...

**Comment by eddelbuettel** [comment]
@kevinushey Have a quick glance over morning coffee, this should now be "final" if we get real lucky.

**Comment by kevinushey** [comment]
LGTM; thanks for tidying everything up!

**Comment by eddelbuettel** [comment]
Thanks for getting the ball rolling with the PR!

**Pull request merged**
