### PR TITLE
Add conversion & unit tests for dgR, dtR & dsRMatrix

### PR DESCRIPTION
**Pull request by binxiangni**
In order to solve #17 and #114. And there is a piece of codes using the algorithm from [scipy](https://github.com/scipy/scipy/blob/master/scipy/sparse/sparsetools/csr.h#L436). I have added a reference to that. What else should I do to avoid violating the copy rights? @coatless @eddelbuettel @thirdwing 

Btw, I squash and merge a branch called Rsparse to the master, but now the commit history still shows up here. I know the reason might be that I didn't squash and merge the previous commits, which leads to a messy timeline. :(

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I think you are doing something wrong.

You have not pulled or merged or ... the master branch.  Most of these commits here we already accounted for.

**Comment by binxiangni** [comment]
@eddelbuettel Perhaps I should sync the newest RcppCore/RcppArmadillo to my repo binxiangni/RcppArmadillo first and then commit on that?

**Comment by eddelbuettel** [comment]
It is worth trying one or two things with git.  You can rename your current RcppArmadillo working directory and copy of the repo -- say, `RcppArmadillo-previous` (or add the date, or ...).   

The create a fresh checkout.   That corresponds to our master branch here.

Then try to get both aligned.   You should be able to the the 'working' copy (ie 'previous' above) to just about the same set of commits -- differing only by your _new_ commits made since I merged the branch.

**Comment by coatless** [comment]
Next time around, run `git pull --rebase <remote-name> <branch-name>` before starting on a PR. This should bring your branch up to the present base without a "Merge branch 'master' of github.com:user/repo"

See [Atlassian's Git Rebasing](https://www.atlassian.com/git/tutorials/rewriting-history) for more.

**Comment by eddelbuettel** [comment]
Why rebase and not just merge?  The language about 'new commits' tends to confuse me because I do want the existing commits, not the old changes recommitted as new ones. 

I think what I do in such a case is to
- pull the remote master (ie this repository) to be current
- branch cleanly ie with a fresh `git checkout -b feature/newstuff`  which then contains all of master

But this is git so there are probably half a dozen ways...

**Comment by eddelbuettel** [comment]
That looks much better :100:

**Comment by eddelbuettel** [comment]
Looks really good.  Two quick questions:

1) You mentioned
> And there is a piece of codes using the algorithm from scipy.
Where is that? Does it need a attribution in the file header (i.e. something like 'Portions taken from file abc.py written by D, E and F and released under copyright G' ?)

2) So what did you do for the cleaner PR?  Just a pull from our master, and push?   It did the right thing as all the commits we already accounted

**Comment by binxiangni** [comment]
1. 

You can look at the reference [here](https://github.com/binxiangni/RcppArmadillo/blob/master/inst/include/RcppArmadilloAs.h#L265). If attribution can be added, that would be great. It can be "Portions taken from file [csr.h](https://github.com/scipy/scipy/blob/master/scipy/sparse/sparsetools/csr.h#L436) written by SciPy developers and released under Copyright 2017 SciPy developers. "(?) I only find that on their website.

2. 

- I git clone binxiangni/RcppArmadillo to local and reset to the commit without all my previous commits. 

- pull from RcppCore/RcppArmadillo

- paste the three modified files to the local repo, git add and git commit

- git push -f to binxiangni/RcppArmadillo

**Comment by eddelbuettel** [comment]
1. My bad. I missed the reference.  Yes. something like that would do.  I may be hard to get concise author reference for SciPy.  

2. I see. I didn't account for  the `git push -f` possibility.  

All good.

**Comment by eddelbuettel** [comment]
All merged.  

@binxiangni can you maybe write a short note at each of e #17 and #114 and close them, if appropriate, now that this is merged?

**Pull request merged**
