### PR TITLE
dgt, dtt and dst types converted by native batch constructor

### PR DESCRIPTION
**Pull request by sgsokol**
Here we go with PR for issue #173 ... but I am afraid to make again not very clean PR as it includes (I don't know why) inst/NEWS.Rd which I didn't touch. The modified version of NEWS.rd came from my earlier syncro with the main repo.
Anyhow, the patch adds very little of code (but removes much more) so if the PR is not acceptable as it is, may be copy/paste will be possible option?
On my side, unit tests pass OK and timing measurements give similar results both for asSpMat(dgt) and dgt2spmatNative(dgt) from the code posted in #173.

### CODE REVIEW

**Comment by coatless** [comment]
Nicely done. However, is there anyway you could update your branch to avoid having all of these old commits? Hard to easily tell the difference.... 

```
git rebase master
git push --force-with-lease
```

**Comment by eddelbuettel** [comment]
Thanks for the PR.  

A rebase, or simply restart which a fresh fork, would be good.

Also for version, just increment (or create) a new minor please, i.e `Version: 0.7.960.1.2.1` as a first revision to 0.7.960.1.2.

**Comment by sgsokol** [comment]
I was preparing a new PR based on a clean re-fork when I saw that you already committed 0f3d81b. If I submit a new PR it will overlap, won't it?

**Comment by sgsokol** [comment]
My bad, a green check sign means Travis CI build OK not a commit. So I continue with a new PR.

**Comment by binxiangni** [comment]
Personally, I prefer to keep the `dgt`, `dtt` and `dst` separately under different `else if` to keep the consistency and readability, although it may lead to duplicate code. If you think now is good, I'll integrate other conversion.

**Comment by sgsokol** [comment]
Sure, you keep the style of code that you prefer. I wanted just to bring a general idea.

**Comment by coatless** [comment]
This PR is now in #174. It can be closed.

**Pull request closed without merging**
