### PR TITLE
workaround to mitigate possible interference from a system-level installation of Armadillo

### PR DESCRIPTION
**Pull request by conradsnicta**
related to https://github.com/RcppCore/RcppArmadillo/issues/280 and https://github.com/RcppCore/RcppArmadillo/issues/264

### CODE REVIEW

**Comment by conradsnicta** [comment]
The underlying issue stems from `#include <armadillo>`.  It seems that under clang, the current directory is not searched first (ie. the directory where `RcppArmadillo.h` lives).

Instead, clang probably first searches directories like `/usr/include/`, `/usr/local/include` and whatever the usual places are on macOS. This in turn would pick up the system-level installation of Armadillo first, instead of the Armadillo embedded within RcppArmadillo.

CC: @coatless

**Comment by eddelbuettel** [comment]
Slightly confused here:  If it is only for `clang` (and possibly only for the OS from Cupertino) then why would we undef unconditionally for all use cases?

**Comment by conradsnicta** [comment]
It doesn't hurt in all use cases.  There are two possible compilation paths: (1) either the system-level of Armadillo is picked up,  or (2) the Armadillo embedded with RcppAramdillo is picked up.

In both cases you do not want the wrapper to be enabled within the context of RcppArmadillo.  (The wrapper is the armadillo run-time library).

In case (2) not using the wrapper is the default operation, so `#define ARMA_DONT_USE_WRAPPER` doesn't do anything.

In case (1) we need to ensure the wrapper is not enabled, so `#define ARMA_DONT_USE_WRAPPER` is helpful.

**Comment by coatless** [comment]
The solution proposed by @conradsnicta fixes the compilation issue if `armadillo` is installed system-wide via `brew`. I'd recommend merging based on @conradsnicta's https://github.com/RcppCore/RcppArmadillo/pull/281#issuecomment-563046204 explanation.

For posterity's sake, we have: 

<details>
<summary>Compiling RcppArmadillo package from source *with* fix. (Clean build)</summary>

```bash
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RcppArmadillo)
```
</details>

<details>
<summary>Compiling the RcppArmadillo package from source *without* proposed define fix. (Error build) </summary>

Mirrors #280 error.

```bash
Error: package or namespace load failed for ‘RcppArmadillo’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so, 6): Symbol not found: _wrapper2_ddot_
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so
Error: loading failed
Execution halted
ERROR: loading failed
```

</details>

**Pull request merged**
