### PR TITLE
add ARMA_IGNORE_DEPRECATED_MARKER option

### PR DESCRIPTION
**Pull request by conradsnicta**
@eddelbuettel as per discussion via email

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That variant works for me too.

As I said, no rush, and I am (forced to be) waiting on CRAN anyway so no need to drop PR that just mean I'll either have to rebase them, or squash.

Also, as you are now 2 for 2 in two days:  Our scheme here includes a ChangeLog entry with date + author for each commit.  Please add them.

**Comment by conradsnicta** [comment]
followup PR for the ChangeLog: #390

**Comment by eddelbuettel** [comment]
Just edit the branch you're in.  We do not need another PR for just a Changelog.

**Comment by conradsnicta** [comment]
no problem.  please don't include any of my email addresses in the changelog

**Comment by conradsnicta** [comment]
I won't have time to do further editing via GH.  Sent the patch via email.

**Comment by eddelbuettel** [comment]
Sure -- Maybe in due time I get Gitlab sorted out and may be able to re-fork your repo as my four-year old fork no longer wanted to play along with your current state (possibly due to forced pushed on the main branch...).

**Pull request closed without merging**
