### PR TITLE
add warning for nonstandard macOS builds

### PR DESCRIPTION
**Pull request by kthohr**
Addresses #224. On a macOS system using gcc7:
```
* installing *source* package ‘RcppArmadillo’ ...
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++-mp-7 accepts -g... yes
checking how to run the C++ preprocessor... g++-mp-7 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++-mp-7 accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 7.3.0
checking for macOS... found
checking for macOS Apple compiler... not found
checking for clang compiler... not found
configure: WARNING: unsupported macOS build detected; if anything breaks, you keep the pieces.
checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
```
I also reverted a change to the m4 macro used on line 15 (`m4_esyscmgd_s`), was that an error? My version of autoconf complained...

### CODE REVIEW

**Comment by kthohr** [comment]
Hmm. The sparse matrix tests are throwing up an error:
```
ERROR in test.csc2dgc: Error in spmat$getformat : $ operator not defined for this S4 class
```

**Comment by binxiangni** [comment]
I tested the csc, coo, and csr matrix and found out that only csc matrix is automatically converted to dgcMatrix, so it doesn't have any method from Python side. I checked the [changelog](https://github.com/cran/reticulate/blob/master/NEWS.md) of reticulate, which says 

> Added support for conversion between Matrix::dgCMatrix objects in R and Scipy CSC matrices in Python

That's why the test failed. I might fix it tomorrow.

**Comment by kthohr** [comment]
Just added you to my fork, you should be able to push to the `macOS-clang-only` branch

**Comment by eddelbuettel** [comment]
Looks good. Maybe make the line shorter: _if it breaks, you keep the pieces._ ?  And/or more visually apparent?  Or is WARNING good enough?

**Comment by eddelbuettel** [comment]
Nice work.

BTW, I noticed that fedora tests (I think those are both machines by Prof Ripley) and one macOS test at CRAN now show errorrs -- see [here](https://cloud.r-project.org/web/checks/check_results_RcppArmadillo.html).

The macOS test seems to be what we ran into here.  Any idea why the `asSpMat(lm)` would seg.fault?

**Comment by eddelbuettel** [comment]
One other issue: do we now need a versioned `Suggests:` on reticulate (and I am not sure one can -- `Imports:` do, `Suggests:` do not AFAIK) ?  Or make the code conditional on old versus new version?

**Comment by binxiangni** [comment]
````
```{Rcpp}
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
sp_mat testSparse(sp_mat X) {
  return X;
}
```
````

````
```{r}
library(Matrix)
library(RUnit)
m <- Matrix(c(0,0,2:0), 3,5, dimnames=list(LETTERS[1:3],NULL))
lm <- (m > 1)
checkException(testSparse(lm))
```

````

I tried to reproduce the error from `asSpMat(lm)`, but on my macOS, I didn't get segment fault. No idea how to fix it now.

**Comment by eddelbuettel** [comment]
Same here, so I really suspect something with his Fedora setup:

```r
R> sourceCpp("/tmp/pr225.cpp")

R> library(Matrix)

R> library(RUnit)

R> m <- Matrix(c(0,0,2:0), 3,5, dimnames=list(LETTERS[1:3],NULL))

R> lm <- (m > 1)

R> checkException(testSparse(lm))
Error in testSparse(lm) : lgCMatrix is not supported.
[1] TRUE
R> 
```

By the way, there is a nice trick if you add a segment `/*** R` followed by R code and closing `*/` the `sourceCpp()` will run the R snippet for you!  So I made your two pieces the code that follows below.  

Thanks for setting up a minimal example!

```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
sp_mat testSparse(sp_mat X) {
  return X;
}

/*** R
library(Matrix)
library(RUnit)
m <- Matrix(c(0,0,2:0), 3,5, dimnames=list(LETTERS[1:3],NULL))
lm <- (m > 1)
checkException(testSparse(lm))
*/
```

**Pull request merged**
