### PR TITLE
Add conversion & unit tests for dgT, dtT & dsTMatrix

### PR DESCRIPTION
**Pull request by binxiangni**
In order to solve [#17](https://github.com/RcppCore/RcppArmadillo/issues/17) and [#114](https://github.com/RcppCore/RcppArmadillo/issues/114).

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Wait, there seem to some of the same commits in both pull requests. That's generally not a great idea.

**Comment by binxiangni** [comment]
Maybe I should first close this PR.

**Comment by eddelbuettel** [comment]
I now merged #135.  If we're careful we could probably open this and merge it too.

We can either open, and merge (maybe simplest) or cherry pick the last two commits.

In general, let's try to only work on one open PR at a time.  I'm sorry I took four days on the last one but review _is_ useful.

**Comment by eddelbuettel** [comment]
There is however a conflict now so that would have to be resolved first.

**Comment by binxiangni** [comment]
The conflict is due to my deletion of 2 comments on the previously merged codes

**Comment by coatless** [comment]
Might I suggest for this PR that @eddelbuettel uses a merge squash? In essence, the working history of the branch is condensed into one commit that is added into the master. This keeps all of the changes of the PR together without adding the duplicate history from the previous PR back into the master. 

Merge and squash via:

- [GH's PR interface](https://github.com/blog/2141-squash-your-commits)
- [CLI `git`](https://stackoverflow.com/questions/5308816/how-to-use-git-merge-squash)

```
git checkout master
git merge --squash branch_here
git commit
```

**Comment by eddelbuettel** [comment]
Yes. I already used a merge squash on the last one. Trivial from GitHub's GUI.

**Comment by coatless** [comment]
Missed that. Awesome!

**Comment by eddelbuettel** [comment]
No worries, and thanks for the CLI reminder.  Noted, and copied to local README.

**Comment by eddelbuettel** [comment]
Tests find on my end in a branch, so in it goes.  Hurray :)

**Pull request merged**
